project_id = "kclwkzibsueqrtpapeji"

[functions.scrape-lekmanga]
verify_jwt = false

[functions.cloudflare-bypass]
verify_jwt = false

[functions.yugabyte-sync]
verify_jwt = false

[functions.extract-manga-info]
verify_jwt = false

[functions.process-download-queue]
verify_jwt = false

[functions.queue-all-chapters]
verify_jwt = false
