project_id = "kclwkzibsueqrtpapeji"

[functions.scrape-lekmanga]
verify_jwt = true

[functions.cloudflare-bypass]
verify_jwt = true

[functions.yugabyte-sync]
verify_jwt = false

[functions.extract-manga-info]
verify_jwt = true
